import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs'
import { AiFillGithub } from 'react-icons/ai'
import { SiNextdotjs, SiJavascript, SiCss3, SiMongodb, SiReact, SiMaterialui, SiFirebase, SiTailwindcss } from 'react-icons/si'
import { FaNodeJs, FaCcStripe } from 'react-icons/fa'
import blog from '../public/ntheblog.png'
import bucket from '../public/bucket.png'
import estore from '../public/scam-shop.png'
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Subash | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-gray-100 h-max px-10 md:px-20 lg:px-40 dark:bg-gray-900 overflow-auto'>
        <section >
          <nav className=' py-10 mb-12 flex justify-between dark:text-white"'>
            <h1 className=' text-xl dark:text-white'>My Portfolio</h1>
            <ul className=' flex items-center'>
              <li>{!darkMode ? <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl' /> :
                <BsFillSunFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl dark:text-white' />}</li>
              <li><Link href='/Subash-Resume.pdf' 
               target='_blank' rel='noopener noreferrer'
               className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</Link></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Subash</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Full stack webdeveloper</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-gray-200'>
              I am an internet taught Web Developer who can build websites with my knowledge
              in Javascript, Node.js, Express, MongoDB, React, and Next.js.
              I'm passionate about strengthening my knowledge, learning new technologies and building cool web apps.
            </p>
          </div>
          <div className='text-5xl flex justify-center py-3 text-gray-600 dark:text-gray-400'>
            <Link href='https://github.com/SubashD22' target='_blank'><AiFillGithub /></Link>
          </div>
        </section>
        <section className='mt-10'>
          <div className=' text-center'>
            <h3 className=' text-3xl py-1 dark:text-white '> My Projects </h3>
          </div>
          <div className='xl:flex gap-10 '>
            <div className=' text-center bg-gray-200 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-600 sm:p-10 xl:p-5'>
              <Image src={blog} className='rounded-xl' alt='blog' />
              <h3 className=' text-lg font-medium pt-8 pb-2  text-teal-600 dark:text-teal-400' >NT,HE</h3>
              <p className=' py-2 dark:text-gray-200'>
                A Simple blog with CRUD functionality with JWT for authentication and authorization, Cloudinary for image storage and QuillJS for a rich text editor.
              </p>
              <h4 className=' py-4 text-teal-600 dark:text-teal-400'>Tools used</h4>
              <div className='flex flex-wrap gap-10 place-content-center'>
                <SiJavascript className=' text-2xl  dark:text-white ' />
                <SiNextdotjs className=' text-2xl  dark:text-white ' />
                <SiCss3 className=' text-2xl  dark:text-white ' />
                <SiMongodb className=' text-2xl  dark:text-white ' />
                <b className=' dark:text-white '>QillJs</b>
                <b className=' dark:text-white '>Cloudinary</b>
              </div>
              <div className='flex gap-2 place-content-center pt-8 justify-around'>
                <Link href='https://ntheblog.vercel.app/' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>Live</Link>
                <Link href='https://github.com/SubashD22/ntheblog' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>Code</Link>
              </div>
            </div>
            
            <div className=' text-center bg-gray-200 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-600 sm:p-10 xl:p-5 '>
              <Image src={bucket} className='rounded-xl' alt='bucket-app' />
              <h3 className=' text-lg font-medium pt-8 pb-2  text-teal-600 dark:text-teal-400' >BUCKET</h3>
              <p className=' py-2 dark:text-gray-200'>
                A bucket list app with Firebase+MongoDb for authentication, the ability to search data from different APIs, react-beautiful-dnd to reorder the list by drag and drop, and MaterialUI of UI
              </p>
              <h4 className=' py-4 text-teal-600  dark:text-teal-400'>Tools used</h4>
              <div className='flex flex-wrap gap-10 place-content-center'>
                <SiJavascript className=' text-2xl  dark:text-white ' />
                <SiReact className=' text-2xl  dark:text-white ' />
                <SiMaterialui className=' text-2xl  dark:text-white ' />
                <FaNodeJs className=' text-2xl  dark:text-white ' />
                <SiFirebase className='text-2xl  dark:text-white ' />
                <SiMongodb className=' text-2xl  dark:text-white ' />
              </div>
              <div className='flex gap-2 place-content-center pt-8 justify-around'>
                <Link href='https://bucket-ebon.vercel.app/' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md '>Live</Link>
                <Link href='https://github.com/SubashD22/Bucket' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md '>Code</Link>
              </div>
            </div>
            <div className=' text-center bg-gray-200 shadow-lg p-5 rounded-xl my-10 dark:bg-gray-600 sm:p-10 xl:p-5'>
              <Image src={estore} className='rounded-xl' alt='e-commerce' />
              <h3 className=' text-lg font-medium pt-8 pb-2  text-teal-600 dark:text-teal-400' >SCAM SHOP</h3>
              <p className=' py-2 dark:text-gray-200'>
                An E-Commerce Store built using NextJs for the frontend and NodeJs for the backend. It has persistent cart functionality using localstorage, and Stripe for payment.
              </p>
              <h4 className=' py-4 text-teal-600 dark:text-teal-400'>Tools used</h4>
              <div className='flex flex-wrap gap-10 place-content-center'>
                <SiJavascript className=' text-2xl  dark:text-white ' />
                <SiNextdotjs className=' text-2xl  dark:text-white ' />
                <SiCss3 className=' text-2xl  dark:text-white ' />
                <FaCcStripe className=' text-2xl  dark:text-white ' />
                <FaNodeJs className=' text-2xl  dark:text-white ' />
                <SiMongodb className=' text-2xl  dark:text-white ' />
              </div>
              <div className='flex gap-2 place-content-center pt-8 justify-around'>
                <Link href='https://scam-shop.vercel.app/' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>Live</Link>
                <Link href='https://github.com/SubashD22/scam-shop-frontend' target='_blank' className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>Code</Link>
              </div>
            </div>
          </div>
        </section>
        <section>
          
        </section>
      </main>
      <footer className=' text-center bg-gray-100  dark:bg-gray-900 '>
        <h2 className=' dark:text-white'>Made with <span><SiTailwindcss className=' inline text-2xl ' /></span></h2>
      </footer>
    </div >
  )
}
